# Generated by Django 3.1.6 on 2021-02-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetreivedData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=12)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('volume', models.FloatField()),
                ('quoteVolume', models.FloatField()),
                ('percentChange', models.FloatField()),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
